# This file was auto-generated by Fern from our API Definition.

from ..core.client_wrapper import SyncClientWrapper
from .raw_client import RawEligibilityResponseClient
import typing
from ..core.request_options import RequestOptions
from ..types.eligibility_response_response import EligibilityResponseResponse
from ..core.client_wrapper import AsyncClientWrapper
from .raw_client import AsyncRawEligibilityResponseClient


class EligibilityResponseClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEligibilityResponseClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEligibilityResponseClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEligibilityResponseClient
        """
        return self._raw_client

    def get_document_by_id(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EligibilityResponseResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EligibilityResponseResponse
            Success

        Examples
        --------
        from fernstarterpack import Starter

        client = Starter(
            api_key="YOUR_API_KEY",
        )
        client.eligibility_response.get_document_by_id()
        """
        response = self._raw_client.get_document_by_id(request_options=request_options)
        return response.data


class AsyncEligibilityResponseClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEligibilityResponseClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEligibilityResponseClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEligibilityResponseClient
        """
        return self._raw_client

    async def get_document_by_id(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EligibilityResponseResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EligibilityResponseResponse
            Success

        Examples
        --------
        import asyncio

        from fernstarterpack import AsyncStarter

        client = AsyncStarter(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.eligibility_response.get_document_by_id()


        asyncio.run(main())
        """
        response = await self._raw_client.get_document_by_id(request_options=request_options)
        return response.data
