# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import typing
from ..core.serialization import FieldMetadata
from .eligibility_response_response_detail_plan_eligibilitys_item_medicare_part import (
    EligibilityResponseResponseDetailPlanEligibilitysItemMedicarePart,
)
from .eligibility_response_response_detail_plan_eligibilitys_item_part_c import (
    EligibilityResponseResponseDetailPlanEligibilitysItemPartC,
)
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class EligibilityResponseResponseDetailPlanEligibilitysItem(UniversalBaseModel):
    end_date: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="EndDate")] = None
    medicare_part: typing_extensions.Annotated[
        typing.Optional[EligibilityResponseResponseDetailPlanEligibilitysItemMedicarePart],
        FieldMetadata(alias="MedicarePart"),
    ] = None
    part_c: typing_extensions.Annotated[
        typing.Optional[EligibilityResponseResponseDetailPlanEligibilitysItemPartC], FieldMetadata(alias="PartC")
    ] = None
    start_date: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="StartDate")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
