# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import datetime as dt
from ..core.serialization import FieldMetadata
from .eligibility_response_response_detail_subscriber_gender import EligibilityResponseResponseDetailSubscriberGender
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class EligibilityResponseResponseDetailSubscriber(UniversalBaseModel):
    birthdate: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="Birthdate")]
    first_name: typing_extensions.Annotated[str, FieldMetadata(alias="FirstName")]
    gender: typing_extensions.Annotated[
        EligibilityResponseResponseDetailSubscriberGender, FieldMetadata(alias="Gender")
    ]
    last_name: typing_extensions.Annotated[str, FieldMetadata(alias="LastName")]
    medicare_id: typing_extensions.Annotated[str, FieldMetadata(alias="MedicareID")] = pydantic.Field()
    """
    Member’s Medicare ID
    (HICN or MBI)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
