# This file was auto-generated by Fern from our API Definition.

import typing

EligibilityResponseResponseDetailRejectionReason = typing.Union[
    typing.Literal["Subscriber or Insured not found", "Duplicate Subscriber or Insured ID"], typing.Any
]
