# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing_extensions
from .eligibility_response_response_detail import EligibilityResponseResponseDetail
from ..core.serialization import FieldMetadata
from .eligibility_response_response_header import EligibilityResponseResponseHeader
import typing
from .eligibility_response_response_meta import EligibilityResponseResponseMeta
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class EligibilityResponseResponse(UniversalBaseModel):
    detail: typing_extensions.Annotated[EligibilityResponseResponseDetail, FieldMetadata(alias="Detail")]
    header: typing_extensions.Annotated[EligibilityResponseResponseHeader, FieldMetadata(alias="Header")]
    meta: typing_extensions.Annotated[typing.Optional[EligibilityResponseResponseMeta], FieldMetadata(alias="Meta")] = (
        None
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
