# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import typing
from .eligibility_response_response_detail_references_item_ref_qual import (
    EligibilityResponseResponseDetailReferencesItemRefQual,
)
from ..core.serialization import FieldMetadata
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class EligibilityResponseResponseDetailReferencesItem(UniversalBaseModel):
    ref_qual: typing_extensions.Annotated[
        typing.Optional[EligibilityResponseResponseDetailReferencesItemRefQual], FieldMetadata(alias="RefQual")
    ] = None
    reference: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="Reference")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
