# This file was auto-generated by Fern from our API Definition.

import typing

EligibilityResponseResponseDetailPlanEligibilitysItemMedicarePart = typing.Union[
    typing.Literal["A", "B", "C"], typing.Any
]
