# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import typing
from ..core.serialization import FieldMetadata
import pydantic
from .eligibility_response_response_detail_plan_eligibilitys_item import (
    EligibilityResponseResponseDetailPlanEligibilitysItem,
)
from .eligibility_response_response_detail_references_item import EligibilityResponseResponseDetailReferencesItem
from .eligibility_response_response_detail_rejection_reason import EligibilityResponseResponseDetailRejectionReason
from .eligibility_response_response_detail_subscriber import EligibilityResponseResponseDetailSubscriber
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class EligibilityResponseResponseDetail(UniversalBaseModel):
    originating_company_id: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="OriginatingCompanyID")
    ] = pydantic.Field(default=None)
    """
    The number ‘9’ plus the
    RRE number. The RRE
    number must contain 9
    digits. Populate leading
    positions with zeros.
    """

    plan_eligibilitys: typing_extensions.Annotated[
        typing.Optional[typing.List[EligibilityResponseResponseDetailPlanEligibilitysItem]],
        FieldMetadata(alias="PlanEligibilitys"),
    ] = None
    references: typing_extensions.Annotated[
        typing.Optional[typing.List[EligibilityResponseResponseDetailReferencesItem]], FieldMetadata(alias="References")
    ] = None
    rejection_reason: typing_extensions.Annotated[
        typing.Optional[EligibilityResponseResponseDetailRejectionReason], FieldMetadata(alias="RejectionReason")
    ] = None
    responsible_reporting_entity: typing_extensions.Annotated[
        str, FieldMetadata(alias="ResponsibleReportingEntity")
    ] = pydantic.Field()
    """
    9-digit Responsible
    Reporting Entity (RRE)
    number assigned by
    COB.
    The RRE number must
    contain 9 digits.
    Populate leading
    positions with zeros.
    """

    subscriber: typing_extensions.Annotated[
        EligibilityResponseResponseDetailSubscriber, FieldMetadata(alias="Subscriber")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
