# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from .raw_client import RawEligibilityInquiryClient
from .types.eligibility_inquiry_request_detail import EligibilityInquiryRequestDetail
from .types.eligibility_inquiry_request_header import EligibilityInquiryRequestHeader
from .types.eligibility_inquiry_request_meta import EligibilityInquiryRequestMeta
from ..core.request_options import RequestOptions
from ..core.client_wrapper import AsyncClientWrapper
from .raw_client import AsyncRawEligibilityInquiryClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EligibilityInquiryClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEligibilityInquiryClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEligibilityInquiryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEligibilityInquiryClient
        """
        return self._raw_client

    def medicare_ob_process_main(
        self,
        *,
        detail: EligibilityInquiryRequestDetail,
        header: EligibilityInquiryRequestHeader,
        meta: typing.Optional[EligibilityInquiryRequestMeta] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        detail : EligibilityInquiryRequestDetail

        header : EligibilityInquiryRequestHeader

        meta : typing.Optional[EligibilityInquiryRequestMeta]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Success

        Examples
        --------
        import datetime

        from fernstarterpack import Starter
        from fernstarterpack.eligibility_inquiry import (
            EligibilityInquiryRequestDetail,
            EligibilityInquiryRequestDetailSubscriber,
            EligibilityInquiryRequestHeader,
        )

        client = Starter(
            api_key="YOUR_API_KEY",
        )
        client.eligibility_inquiry.medicare_ob_process_main(
            detail=EligibilityInquiryRequestDetail(
                responsible_reporting_entity="ResponsibleReportingEntity",
                subscriber=EligibilityInquiryRequestDetailSubscriber(
                    birthdate=datetime.datetime.fromisoformat(
                        "2024-01-15 09:30:00+00:00",
                    ),
                    first_name="FirstName",
                    gender="M",
                    last_name="LastName",
                    medicare_id_members_medicare_id_hicn_or_mbi="MedicareIDMember’s Medicare ID (HICN or MBI)",
                ),
            ),
            header=EligibilityInquiryRequestHeader(),
        )
        """
        response = self._raw_client.medicare_ob_process_main(
            detail=detail, header=header, meta=meta, request_options=request_options
        )
        return response.data


class AsyncEligibilityInquiryClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEligibilityInquiryClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEligibilityInquiryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEligibilityInquiryClient
        """
        return self._raw_client

    async def medicare_ob_process_main(
        self,
        *,
        detail: EligibilityInquiryRequestDetail,
        header: EligibilityInquiryRequestHeader,
        meta: typing.Optional[EligibilityInquiryRequestMeta] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        detail : EligibilityInquiryRequestDetail

        header : EligibilityInquiryRequestHeader

        meta : typing.Optional[EligibilityInquiryRequestMeta]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Success

        Examples
        --------
        import asyncio
        import datetime

        from fernstarterpack import AsyncStarter
        from fernstarterpack.eligibility_inquiry import (
            EligibilityInquiryRequestDetail,
            EligibilityInquiryRequestDetailSubscriber,
            EligibilityInquiryRequestHeader,
        )

        client = AsyncStarter(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.eligibility_inquiry.medicare_ob_process_main(
                detail=EligibilityInquiryRequestDetail(
                    responsible_reporting_entity="ResponsibleReportingEntity",
                    subscriber=EligibilityInquiryRequestDetailSubscriber(
                        birthdate=datetime.datetime.fromisoformat(
                            "2024-01-15 09:30:00+00:00",
                        ),
                        first_name="FirstName",
                        gender="M",
                        last_name="LastName",
                        medicare_id_members_medicare_id_hicn_or_mbi="MedicareIDMember’s Medicare ID (HICN or MBI)",
                    ),
                ),
                header=EligibilityInquiryRequestHeader(),
            )


        asyncio.run(main())
        """
        response = await self._raw_client.medicare_ob_process_main(
            detail=detail, header=header, meta=meta, request_options=request_options
        )
        return response.data
