# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import typing
from .eligibility_inquiry_request_detail_reference import EligibilityInquiryRequestDetailReference
from ...core.serialization import FieldMetadata
import pydantic
from .eligibility_inquiry_request_detail_subscriber import EligibilityInquiryRequestDetailSubscriber
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class EligibilityInquiryRequestDetail(UniversalBaseModel):
    reference: typing_extensions.Annotated[
        typing.Optional[EligibilityInquiryRequestDetailReference], FieldMetadata(alias="Reference")
    ] = None
    responsible_reporting_entity: typing_extensions.Annotated[
        str, FieldMetadata(alias="ResponsibleReportingEntity")
    ] = pydantic.Field()
    """
    9-digit Responsible
    Reporting Entity (RRE)
    number assigned by
    COB.
    The RRE number must
    contain 9 digits.
    Populate leading
    positions with zeros.
    """

    subscriber: typing_extensions.Annotated[
        EligibilityInquiryRequestDetailSubscriber, FieldMetadata(alias="Subscriber")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
