# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
import typing_extensions
import typing
import datetime as dt
from ...core.serialization import FieldMetadata
from .eligibility_inquiry_request_meta_settings import EligibilityInquiryRequestMetaSettings
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class EligibilityInquiryRequestMeta(UniversalBaseModel):
    received_date_time: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="ReceivedDateTime")
    ] = None
    settings: typing_extensions.Annotated[
        typing.Optional[EligibilityInquiryRequestMetaSettings], FieldMetadata(alias="Settings")
    ] = None
    tags: typing_extensions.Annotated[typing.Optional[typing.List[str]], FieldMetadata(alias="Tags")] = None
    id: typing.Optional[str] = None
    source: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
