# This file was auto-generated by Fern from our API Definition.

import typing
from .eligibility_inquiry_request_detail_reference_one import EligibilityInquiryRequestDetailReferenceOne

EligibilityInquiryRequestDetailReference = typing.Union[str, EligibilityInquiryRequestDetailReferenceOne]
