# This file was auto-generated by Fern from our API Definition.

import typing

EligibilityInquiryRequestDetailReference = typing.Union[
    str, typing.Literal["IG"], typing.Literal["NQ"], typing.Literal["EA"]
]
